name = "spinmachoapp-com-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmachoapp.com.de"
HMAC_KEY = "590bd18c6180e34909ce1522159c2f0fce3682b92f68b426087f7d13520bc992"
COOKIE_NAME = "56v"
PLAY_PATH = "play-now"
BUTTON_ID = "p2a7c78673be16379888297067386cfc4"
GATE_SALT = "af0fe8a6e6779007"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "fpc0"
CTA_SELECTOR = ".play-button"
